branch-defaults:
  main:
    environment: gujarat-police-dev
    group_suffix: null
global:
  application_name: gujarat_police_backend
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

deploy:
  artifact: target/gujarat_police-0.0.1-SNAPSHOT.jar
